### ISSUE TITLE
fog-1.33.0 conflicts with fog (~> 1.23.0)

### ISSUE THREAD

**Issue by jsvazic** [chef/knife-ec2#350]
I have installed chefdk 0.7.0-1 on my Ubuntu 14.04.03 desktop and have downloaded my Chef SSL cert via knife.  I verified everything using `chef verify`, which passed, and then I installed knife-ec2 via:

    chef gem install knife-ec2

which completes successfully.  However, when I try to run:

    knife ec2 server list

I get the following:

```
/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2104:in `raise_if_conflicts': Unable to activate knife-ec2-0.10.0, because fog-1.33.0 conflicts with fog (~> 1.23.0) (Gem::ConflictError)
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1282:in `activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:198:in `rescue in try_activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:195:in `try_activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /home/john/.chefdk/gem/ruby/2.1.0/gems/knife-ec2-0.10.0/lib/chef/knife/ec2_server_list.rb:20:in `<top (required)>'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `load'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `block in load_commands'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `each'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `load_commands'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:128:in `load_commands'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:209:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:142:in `run'
	from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:55:in `load'
	from /opt/chefdk/bin/knife:55:in `<main>'
```

Any ideas?

**Comment by Dee-2015** [comment]
Hi, I stumbled against (almost) the same problem, see also https://github.com/chef/knife-ec2/issues/281

**Comment by tas50** [comment]
The latest knife-ec2 (0.11) fixes this.
