### ISSUE TITLE
undefined local variable or method `chef_version', possible package version issues

### ISSUE THREAD

**Issue by nicholasserra** [chef/knife-ec2#448]
Hello, hoping someone may be able to give me some direction on an error i'm seeing. I'm assuming i'm probably out of date or running incompatible versions to be getting this error during bootstrap.

Running:
Ruby 2.2.2
chef (12.15.19, 12.5.1)
knife-ec2 (0.13.0)

The short error is
```
Exception: NameError: undefined local variable or method `chef_version' for #<Chef::Knife::Core::BootstrapContext:0x007f9f3e7bf248>
```

And with verbose output it is 

```
(erubis):23:in `block in evaluate': undefined local variable or method `chef_version' for #<Chef::Knife::Core::BootstrapContext:0x007fbcceab5440> (NameError)
	from /Users/nick/.rvm/gems/ruby-2.2.2@sprintly/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `instance_eval'
	from /Users/nick/.rvm/gems/ruby-2.2.2@sprintly/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `evaluate'
	from /Users/nick/.rvm/gems/ruby-2.2.2@sprintly/gems/chef-12.15.19/lib/chef/knife/bootstrap.rb:364:in `render_template'
	from /Users/nick/.rvm/gems/ruby-2.2.2@sprintly/gems/chef-12.15.19/lib/chef/knife/bootstrap.rb:457:in `ssh_command'
	from /Users/nick/.rvm/gems/ruby-2.2.2@sprintly/gems/chef-12.15.19/lib/chef/knife/bootstrap.rb:436:in `knife_ssh'
	from /Users/nick/.rvm/gems/ruby-2.2.2@sprintly/gems/chef-12.15.19/lib/chef/knife/bootstrap.rb:401:in `run'
	from /Users/nick/.rvm/gems/ruby-2.2.2@sprintly/gems/knife-ec2-0.13.0/lib/chef/knife/ec2_server_create.rb:576:in `run'
	from /Users/nick/.rvm/gems/ruby-2.2.2@sprintly/gems/chef-12.15.19/lib/chef/knife.rb:429:in `block in run_with_pretty_exceptions'
	from /Users/nick/.rvm/gems/ruby-2.2.2@sprintly/gems/chef-12.15.19/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /Users/nick/.rvm/gems/ruby-2.2.2@sprintly/gems/chef-12.15.19/lib/chef/knife.rb:428:in `run_with_pretty_exceptions'
	from /Users/nick/.rvm/gems/ruby-2.2.2@sprintly/gems/chef-12.15.19/lib/chef/knife.rb:219:in `run'
	from /Users/nick/.rvm/gems/ruby-2.2.2@sprintly/gems/chef-12.15.19/lib/chef/application/knife.rb:156:in `run'
	from /Users/nick/.rvm/gems/ruby-2.2.2@sprintly/gems/chef-12.15.19/bin/knife:25:in `<top (required)>'
	from /Users/nick/.rvm/gems/ruby-2.2.2@sprintly/bin/knife:23:in `load'
	from /Users/nick/.rvm/gems/ruby-2.2.2@sprintly/bin/knife:23:in `<main>'
	from /Users/nick/.rvm/gems/ruby-2.2.2@sprintly/bin/ruby_executable_hooks:15:in `eval'
	from /Users/nick/.rvm/gems/ruby-2.2.2@sprintly/bin/ruby_executable_hooks:15:in `<main>'
```

Thanks in advance for any help :)

**Comment by nicholasserra** [comment]
This ended up being an invalid variable in the bootstrap template.
