### ISSUE TITLE
knife ec2 server create fails while connecting to node 

### ISSUE THREAD

**Issue by dheerajd-msys** [chef/knife-ec2#567]
# Version:

knife-ec2 v0.19.16 and chef v15.0.233 on workstation

# Environment:

Ubuntu 18.04

# Scenario:

```
knife ec2 server create -N "dh-test-node-ubu" -I "ami-005bdb005fb00e791" --identity-file 'E:\Backup\Project\chef-starter\chef-repo\identity-key-aws\dh-aws-key.pem' --ssh-user ubuntu --bootstrap-protocol ssh --flavor t2.medium -c "E:\Backup\Project\chef-starter\chef-repo\.chef\knife.rb" --ssh-key "dh-aws-key"
```

# Steps to Reproduce:

Please run above command to create the server from workstation.

# Expected Result:

It should create the server in aws and bootstrap the server

# Actual Result:

```Exception: NameError: uninitialized constant Net::SSH```
# Stacktrace
```
Traceback (most recent call last):
        10: from C:/opscode/chef/embedded/bin/knife:23:in `<main>'
         9: from C:/opscode/chef/embedded/bin/knife:23:in `load'
         8: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/bin/knife:24:in `<top (required)>'
         7: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/lib/chef/application/knife.rb:162:in `run'
         6: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/lib/chef/knife.rb:221:in `run'
         5: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/lib/chef/knife.rb:459:in `run_with_pretty_exceptions'
         4: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/lib/chef/local_mode.rb:41:in `with_server_connectivity'
         3: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/lib/chef/knife.rb:460:in `block in run_with_pretty_exceptions'
         2: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-ec2-0.19.16/lib/chef/knife/ec2_server_create.rb:632:in `run'
         1: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-ec2-0.19.16/lib/chef/knife/ec2_server_create.rb:1246:in `wait_for_sshd'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-ec2-0.19.16/lib/chef/knife/ec2_server_create.rb:1260:in `get_ssh_gateway_for': uninitialized constant Net::SSH (NameError)
```

**Comment by dheerajd-msys** [comment]
Although https://github.com/chef/knife-ec2/pull/569 fixes initial issue to `ssh` I am getting below error now while proceeding above command : 
```
Traceback (most recent call last):
        13: from C:/opscode/chef/embedded/bin/knife:23:in `<main>'
        12: from C:/opscode/chef/embedded/bin/knife:23:in `load'
        11: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/bin/knife:24:in `<top (required)>'
        10: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/application/knife.rb:162:in `run'
         9: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/knife.rb:221:in `run'
         8: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/knife.rb:468:in `run_with_pretty_exceptions'
         7: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/local_mode.rb:41:in `with_server_connectivity'
         6: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/knife.rb:469:in `block in run_with_pretty_exceptions'
         5: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-ec2-0.19.16/lib/chef/knife/ec2_server_create.rb:636:in `run'
         4: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/knife/bootstrap.rb:526:in `run'
         3: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/knife/bootstrap.rb:660:in `verify_deprecated_flags!'
         2: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/knife/bootstrap.rb:660:in `each'
         1: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/knife/bootstrap.rb:662:in `block in verify_deprecated_flags!'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/knife.rb:380:in `config_source': undefined method `include?' for nil:NilClass (NoMethodError)
```
