### ISSUE TITLE
knife ec2 server create fails while bootstrap to windows node

### ISSUE THREAD

**Issue by dheerajd-msys** [chef/knife-ec2#568]
# Version:

knife-ec2 v0.19.16 and chef v15.0.238 on workstation

# Environment:

Windows 2012 R2

# Scenario:

```
knife ec2 server create -N dh-win-tag-win -I ami-0395238cb927001d5 -f t2.micro --winrm-user '.\<user-name>' --winrm-password '<password>' --user-data 'E:\Backup\Project\dh-user-data-ec2.ps1' --winrm-transport ssl --winrm-ssl-verify-mode verify_none -
-chef-tag "owner" --aws-tag "foo=bar" --aws-tag "baz=dull" -c 'E:\Backup\Project\chef-starter\chef-repo\.chef\knife.rb'  -VV
```

# Steps to Reproduce:

Please run above command to create the server from workstation.

# Expected Result:

It should create the server in AWS and bootstrap the server

# Actual Result:

`uninitialized constant Knife (NameError)`

# Stacktrace
```
Bootstrapping Chef on ec2-54-214-127-215.us-west-2.compute.amazonaws.com
Traceback (most recent call last):
        12: from C:/opscode/chef/embedded/bin/knife:23:in `<main>'
        11: from C:/opscode/chef/embedded/bin/knife:23:in `load'
        10: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/bin/knife:24:in `<top (required)>'
         9: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/lib/chef/application/knife.rb:162:in `run'
         8: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/lib/chef/knife.rb:221:in `run'
         7: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/lib/chef/knife.rb:459:in `run_with_pretty_exceptions'
         6: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/lib/chef/local_mode.rb:41:in `with_server_connectivity'
         5: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/lib/chef/knife.rb:460:in `block in run_with_pretty_exceptions'
         4: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-ec2-0.19.16/lib/chef/knife/ec2_server_create.rb:629:in `run'
         3: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-windows-1.9.6/lib/chef/knife/bootstrap_windows_winrm.rb:60:in `run'
         2: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-windows-1.9.6/lib/chef/knife/bootstrap_windows_base.rb:332:in `bootstrap'
         1: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-windows-1.9.6/lib/chef/knife/bootstrap_windows_base.rb:374:in `create_bootstrap_bat_command'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-windows-1.9.6/lib/chef/knife/bootstrap_windows_base.rb:234:in `load_template': uninitialized constant Knife (NameError)
```

**Comment by dheerajd-msys** [comment]
Identified that **_USER_DATA_** script requires user should be added in Administrators group for setting winrm configurations on node and there is no need to pass `--winrm-transport ssl, --winrm-ssl-verify-mode verify_none` with chef 15. These options are changed to `--winrm-ssl` and `--winrm-no-verify-cert` respectively in chef 15 as per https://github.com/chef/chef/blob/master/RELEASE_NOTES.md#changed-flags.

[README](https://github.com/chef/knife-ec2/pull/588) is updated for _**USER_DATA**_
