### ISSUE TITLE
Chef 15: knife ec2 server create fails with ERROR: Train::PlatformDetectionFailed:

### ISSUE THREAD

**Issue by dheerajd-msys** [chef/knife-ec2#572]
# Version:

knife-ec2 v0.19.16 and chef v15.0.288 on workstation

**Edit Update** : 
chef v15.0.293 on workstation also causes the issue

# Environment:

Ubuntu 18.04

# Scenario:
```
knife ec2 server create -N "dh-test-node-ubu" -I "ami-005bdb005fb00e791" --identity-file 'E:\Backup\Project\chef-starter\chef-repo\identity-key-aws\dh-aws-key.pem' --ssh-user ubuntu --bootstrap-protocol ssh --flavor t2.micro -c "E:\Backup\Project\chef-starter\chef-repo\.chef\knife.rb"
```
# Steps to Reproduce:
Please run above command to create the server from workstation.

# Expected Result:
It should create the server in AWS and bootstrap the server

# Actual Result:
```
Traceback (most recent call last):
        21: from C:/opscode/chef/embedded/bin/knife:23:in `<main>'
        20: from C:/opscode/chef/embedded/bin/knife:23:in `load'
        19: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.288-universal-mingw32/bin/knife:24:in `<top (required)>'
        18: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.288-universal-mingw32/lib/chef/application/knife.rb:162:in `run'
        17: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.288-universal-mingw32/lib/chef/knife.rb:221:in `run'
        16: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.288-universal-mingw32/lib/chef/knife.rb:473:in `run_with_pretty_exceptions'
        15: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.288-universal-mingw32/lib/chef/local_mode.rb:41:in `with_server_connectivity'
        14: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.288-universal-mingw32/lib/chef/knife.rb:474:in `block in run_with_pretty_exceptions'
        13: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-ec2-0.19.16/lib/chef/knife/ec2_server_create.rb:636:in `run'
        12: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.288-universal-mingw32/lib/chef/knife/bootstrap.rb:552:in `run'
        11: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.288-universal-mingw32/lib/chef/knife/bootstrap.rb:601:in `connect!'
        10: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.288-universal-mingw32/lib/chef/knife/bootstrap.rb:632:in `do_connect'
         9: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.288-universal-mingw32/lib/chef/knife/bootstrap/train_connector.rb:69:in `connect!'
         8: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.288-universal-mingw32/lib/chef/knife/bootstrap/train_connector.rb:56:in `connection'
         7: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.1.0/lib/train/transports/ssh.rb:82:in `connection'
         6: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.1.0/lib/train/transports/ssh.rb:239:in `create_new_connection'
         5: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.1.0/lib/train/transports/ssh.rb:239:in `new'
         4: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.1.0/lib/train/transports/ssh_connection.rb:53:in `initialize'
         3: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.1.0/lib/train/extras/command_wrapper.rb:165:in `load'
         2: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.1.0/lib/train/plugins/base_connection.rb:110:in `platform'
         1: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.1.0/lib/train/platforms/detect.rb:9:in `scan'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.1.0/lib/train/platforms/detect/scanner.rb:41:in `scan': Sorry, we are unable to detect your platform (Train::PlatformDetectionFailed)
```

**Comment by dheerajd-msys** [comment]
I've observed that this issue is due to our change from https://github.com/chef/chef/pull/8506.

**Comment by dheerajd-msys** [comment]
Facing this issue with latest `chef v15.0.293` as well as provided in stack-trace below :
```
Traceback (most recent call last):
        21: from E:/Backup/Project/Chef_Repo/knife-ec2/pkg/ruby/2.6.0/bin/knife:23:in `<main>'
        20: from E:/Backup/Project/Chef_Repo/knife-ec2/pkg/ruby/2.6.0/bin/knife:23:in `load'
        19: from E:/Backup/Project/Chef_Repo/knife-ec2/pkg/ruby/2.6.0/gems/chef-15.0.293-universal-mingw32/bin/knife:24:in `<top (required)>'
        18: from E:/Backup/Project/Chef_Repo/knife-ec2/pkg/ruby/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/application/knife.rb:162:in `run'
        17: from E:/Backup/Project/Chef_Repo/knife-ec2/pkg/ruby/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/knife.rb:221:in `run'
        16: from E:/Backup/Project/Chef_Repo/knife-ec2/pkg/ruby/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/knife.rb:473:in `run_with_pretty_exceptions'
        15: from E:/Backup/Project/Chef_Repo/knife-ec2/pkg/ruby/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/local_mode.rb:41:in `with_server_connectivity'
        14: from E:/Backup/Project/Chef_Repo/knife-ec2/pkg/ruby/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/knife.rb:474:in `block in run_with_pretty_exceptions'
        13: from E:/Backup/Project/Chef_Repo/knife-ec2/lib/chef/knife/ec2_server_create.rb:635:in `run'
        12: from E:/Backup/Project/Chef_Repo/knife-ec2/pkg/ruby/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/knife/bootstrap.rb:548:in `run'
        11: from E:/Backup/Project/Chef_Repo/knife-ec2/pkg/ruby/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/knife/bootstrap.rb:598:in `connect!'
        10: from E:/Backup/Project/Chef_Repo/knife-ec2/pkg/ruby/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/knife/bootstrap.rb:647:in `do_connect'
         9: from E:/Backup/Project/Chef_Repo/knife-ec2/pkg/ruby/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/knife/bootstrap/train_connector.rb:69:in `connect!'
         8: from E:/Backup/Project/Chef_Repo/knife-ec2/pkg/ruby/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/knife/bootstrap/train_connector.rb:56:in `connection'
         7: from E:/Backup/Project/Chef_Repo/knife-ec2/pkg/ruby/2.6.0/gems/train-core-2.1.0/lib/train/transports/ssh.rb:82:in `connection'
         6: from E:/Backup/Project/Chef_Repo/knife-ec2/pkg/ruby/2.6.0/gems/train-core-2.1.0/lib/train/transports/ssh.rb:238:in `create_new_connection'
         5: from E:/Backup/Project/Chef_Repo/knife-ec2/pkg/ruby/2.6.0/gems/train-core-2.1.0/lib/train/transports/ssh.rb:238:in `new'
         4: from E:/Backup/Project/Chef_Repo/knife-ec2/pkg/ruby/2.6.0/gems/train-core-2.1.0/lib/train/transports/ssh_connection.rb:53:in `initialize'
         3: from E:/Backup/Project/Chef_Repo/knife-ec2/pkg/ruby/2.6.0/gems/train-core-2.1.0/lib/train/extras/command_wrapper.rb:165:in `load'
         2: from E:/Backup/Project/Chef_Repo/knife-ec2/pkg/ruby/2.6.0/gems/train-core-2.1.0/lib/train/plugins/base_connection.rb:110:in `platform'
         1: from E:/Backup/Project/Chef_Repo/knife-ec2/pkg/ruby/2.6.0/gems/train-core-2.1.0/lib/train/platforms/detect.rb:9:in `scan'
E:/Backup/Project/Chef_Repo/knife-ec2/pkg/ruby/2.6.0/gems/train-core-2.1.0/lib/train/platforms/detect/scanner.rb:41:in `scan': Sorry, we are unable to detect your platform (Train::PlatformDetectionFailed)
```

**Comment by dheerajd-msys** [comment]
If we set `--ssh-user` in our config file i.e `knife.rb` like `knife[:ssh_user] = ubuntu` issue will be resolved.
Ref : https://github.com/chef/chef/pull/8523#issuecomment-492640470
