### ISSUE TITLE
Chef 15: knife ec2 server create fails with Exception: NoMethodError: undefined method `*' for nil:NilClass

### ISSUE THREAD

**Issue by dheerajd-msys** [chef/knife-ec2#573]
# Version:

knife-ec2 v0.19.16 and chef v15.0.293 on workstation

# Environment:

Ubuntu 18.04 as a node

# Scenario:
```
knife ec2 server create -N dh-ubu-04 -I ami-005bdb005fb00e791 --ssh-user ubuntu --ssh-password ubuntu --flavor t2.micro -c "E:\Backup\Project\chef-starter\chef-repo\.chef\knife.rb"
```
# Steps to Reproduce:
Please run above command to create the server from workstation.
# Expected Result:
It should create the server in AWS and bootstrap the server
# Actual Result:
```
Traceback (most recent call last):
        10: from C:/opscode/chef/embedded/bin/knife:23:in `<main>'
         9: from C:/opscode/chef/embedded/bin/knife:23:in `load'
         8: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293-universal-mingw32/bin/knife:24:in `<top (required)>'
         7: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/application/knife.rb:162:in `run'
         6: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/knife.rb:221:in `run'
         5: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/knife.rb:473:in `run_with_pretty_exceptions'
         4: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/local_mode.rb:41:in `with_server_connectivity'
         3: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/knife.rb:474:in `block in run_with_pretty_exceptions'
         2: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-ec2-0.19.16/lib/chef/knife/ec2_server_create.rb:635:in `run'
         1: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/knife/bootstrap.rb:544:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/knife/bootstrap.rb:780:in `warn_on_short_session_timeout': undefined method `*' for nil:NilClass (NoMethodError)
```

**Comment by dheerajd-msys** [comment]
I've got workaround for this issue providing `knife[:session_timeout] = 60` in my `knife.rb`

**Comment by marcparadise** [comment]
Two things here - 

On this side, our default value isn't kicking in, because knife-ec2 does not call merge_config.

We can fix that on the chef side by not assuming the value will always be present. I will open a PR for that.

**Comment by dheerajd-msys** [comment]
Works fine without providing `knife[:session_timeout]` in `knife.rb` now.
