### ISSUE TITLE
Chef 15: knife ec2 server create fails with ERROR: No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by dheerajd-msys** [chef/knife-ec2#575]
# Version:

knife-ec2 v0.19.16 and chef v15.0.293 on workstation (Windows Workstation)

# Environment:

Ubuntu 18.04 Node

# Scenario:

```
bundle exec knife ec2 server create -N dh-ubu-05 -I ami-005bdb005fb00e791 --flavor t2.micro -c "E:\Backup\Project\chef-starter\chef-repo\.chef\knife.rb" -VV
```

# Steps to Reproduce:

Please run above command to create the server from workstation.

# Expected Result:

It should create the server in AWS and bootstrap the server.

# Actual Result:

```
Traceback (most recent call last):
        14: from E:/Backup/Project/Chef_Repo/knife-ec2/.bundle/ruby/2.6.0/bin/knife:23:in `<main>'
        13: from E:/Backup/Project/Chef_Repo/knife-ec2/.bundle/ruby/2.6.0/bin/knife:23:in `load'
        12: from E:/Backup/Project/Chef_Repo/knife-ec2/.bundle/ruby/2.6.0/gems/chef-15.0.293-universal-mingw32/bin/knife:24:in `<top (required)>'
        11: from E:/Backup/Project/Chef_Repo/knife-ec2/.bundle/ruby/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/application/knife.rb:162:in `run'
        10: from E:/Backup/Project/Chef_Repo/knife-ec2/.bundle/ruby/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/knife.rb:221:in `run'
         9: from E:/Backup/Project/Chef_Repo/knife-ec2/.bundle/ruby/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/knife.rb:473:in `run_with_pretty_exceptions'
         8: from E:/Backup/Project/Chef_Repo/knife-ec2/.bundle/ruby/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/local_mode.rb:41:in `with_server_connectivity'
         7: from E:/Backup/Project/Chef_Repo/knife-ec2/.bundle/ruby/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/knife.rb:474:in `block in run_with_pretty_exceptions'
         6: from E:/Backup/Project/Chef_Repo/knife-ec2/lib/chef/knife/ec2_server_create.rb:635:in `run'
         5: from E:/Backup/Project/Chef_Repo/knife-ec2/.bundle/ruby/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/knife/bootstrap.rb:552:in `run'
         4: from E:/Backup/Project/Chef_Repo/knife-ec2/.bundle/ruby/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/knife/bootstrap.rb:529:in `render_template'
         3: from E:/Backup/Project/Chef_Repo/knife-ec2/.bundle/ruby/2.6.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `evaluate'
         2: from E:/Backup/Project/Chef_Repo/knife-ec2/.bundle/ruby/2.6.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `instance_eval'
         1: from (erubis):193:in `block in evaluate'
(erubis):193:in `read': No such file or directory @ rb_sysopen - C:/Users/chef/AppData/Local/Temp/d20190516-14204-3ld6it/dh-ubu-05.pem (Errno::ENOENT)
```

**Comment by dheerajd-msys** [comment]
Similar issue https://github.com/chef/chef/issues/8534

**Comment by dheerajd-msys** [comment]
There was entry of  `validation_key` in my `knife.rb` which resulted this error. This is old registration process which is no longer valid. We need to delete the `validation_key` from directory in order to get pass this error.

**Comment by dheerajd-msys** [comment]
Fixed via https://github.com/chef/chef/pull/8567.
