### ISSUE TITLE
ec2 create server with option --s3-secret is not working and errors out with undefined method `files' for nil:NilClass (NoMethodError) 

### ISSUE THREAD

**Issue by dheerajd-msys** [chef/knife-ec2#589]
# Version:

knife-ec2 v1.0.0 and chef v15.1.8 on workstation

# Environment:

Doesn't matter

# Scenario:

```
bundle exec knife ec2 server create -I ami-005bdb005fb00e791 -N dh-ubu-11  -U ubuntu --connection-protocol ssh --flavor t2.micro -c E:\Backup\Project\chef-starter\chef-repo\.chef\knife.rb -VV --sudo --yes --s3-secret 'https://chef-test-vivek.s3-us-west-2.amazonaws.com/ec2-secrete-file'
```

# Steps to Reproduce:

Please run above command to create the server from workstation.

# Expected Result:

It should create the server in AWS and bootstrap the server

# Actual Result:

`undefined method `files' for nil:NilClass (NoMethodError)`

# Stacktrace
```
SSH Target Address: ec2-54-71-150-56.us-west-2.compute.amazonaws.com(dns_name)
DEBUG: No ssh gateway found, making a direct connection
DEBUG: ssh failed to connect: ec2-54-71-150-56.us-west-2.compute.amazonaws.com
.DEBUG: ssh failed to connect: ec2-54-71-150-56.us-west-2.compute.amazonaws.com
.DEBUG: sshd accepting connections on ec2-54-71-150-56.us-west-2.compute.amazonaws.com, banner is SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.2

done
[fog][DEPRECATION] Fog::Storage::AWS is deprecated, please use Fog::AWS::Storage.
[fog][WARNING] Unrecognized arguments: aws_access_key_id, aws_secret_access_key
Traceback (most recent call last):
        13: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/bin/knife:23:in `<main>'
        12: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/bin/knife:23:in `load'
        11: from E:/Backup/Project/Chef_Repo/chef/bin/knife:24:in `<top (required)>'
        10: from E:/Backup/Project/Chef_Repo/chef/lib/chef/application/knife.rb:162:in `run'
         9: from E:/Backup/Project/Chef_Repo/chef/lib/chef/knife.rb:222:in `run'
         8: from E:/Backup/Project/Chef_Repo/chef/lib/chef/knife.rb:474:in `run_with_pretty_exceptions'
         7: from E:/Backup/Project/Chef_Repo/chef/lib/chef/local_mode.rb:42:in `with_server_connectivity'
         6: from E:/Backup/Project/Chef_Repo/chef/lib/chef/knife.rb:475:in `block in run_with_pretty_exceptions'
         5: from E:/Backup/Project/Chef_Repo/chef/lib/chef/knife/bootstrap.rb:566:in `run'
         4: from E:/Backup/Project/Chef_Repo/knife-ec2/lib/chef/knife/ec2_server_create.rb:452:in `plugin_create_instance!'
         3: from E:/Backup/Project/Chef_Repo/knife-ec2/lib/chef/knife/ec2_server_create.rb:570:in `bootstrap_common_params'
         2: from E:/Backup/Project/Chef_Repo/knife-ec2/lib/chef/knife/ec2_server_create.rb:565:in `s3_secret'
         1: from E:/Backup/Project/Chef_Repo/knife-ec2/lib/chef/knife/s3_source.rb:25:in `fetch'
E:/Backup/Project/Chef_Repo/knife-ec2/lib/chef/knife/s3_source.rb:29:in `body': undefined method `files' for nil:NilClass (NoMethodError)
```

**Comment by dheerajd-msys** [comment]
Verified that this issue is fixed in https://github.com/chef/knife-ec2/pull/587
