### ISSUE TITLE
knife ec2 server create fails with error ERROR: undefined method `delete_on_termination' for nil:NilClass

### ISSUE THREAD

**Issue by dheerajd-msys** [chef/knife-ec2#592]
# Version:

knife-ec2 v0.19.16 and chef v15.1.8 on workstation

# Environment:

Doesn't matter

# Scenario:

```
bundle exec knife ec2 server create -I ami-005bdb005fb00e791 -N dh-ubu-16  -U ubuntu --connection-protocol ssh --flavor t2.micro -c E:\Backup\Project\chef-starter\chef-repo\.chef\knife.rb -VV --sudo --yes --ebs-volume-type io1 --provisioned-iops 100 --ebs-encrypted --ebs-size 8
```

# Steps to Reproduce:
Please run above command to create the server from workstation.
# Expected Result:

Server should created and bootstrapped with ebs configurations in AWS.

# Actual Result:

`ERROR: undefined method `delete_on_termination' for nil:NilClass`

# Stack-trace
```
INFO: Using configuration from E:/Backup/Project/chef-starter/chef-repo/.chef/knife.rb
DEBUG: Checking if we need to accept Chef license to bootstrap node
DEBUG: Reading products and relationships...
DEBUG: Successfully read products and relationships
DEBUG: License acceptance required for chef version: 15
DEBUG: Searching for the following licenses: ["infra-client", "inspec"]
DEBUG: Found license chef_infra_client at C:/Users/chef/.chef/accepted_licenses/chef_infra_client
DEBUG: Found license inspec at C:/Users/chef/.chef/accepted_licenses/inspec
DEBUG: Missing licenses remaining: []
DEBUG: All licenses present
ERROR: undefined method `delete_on_termination' for nil:NilClass
DEBUG: E:/Backup/Project/Chef_Repo/knife-ec2/lib/chef/knife/ec2_server_create.rb:967:in `server_attributes'
E:/Backup/Project/Chef_Repo/knife-ec2/lib/chef/knife/ec2_server_create.rb:342:in `plugin_create_instance!'
E:/Backup/Project/Chef_Repo/chef/lib/chef/knife/bootstrap.rb:566:in `run'
E:/Backup/Project/Chef_Repo/chef/lib/chef/knife.rb:475:in `block in run_with_pretty_exceptions'
E:/Backup/Project/Chef_Repo/chef/lib/chef/local_mode.rb:42:in `with_server_connectivity'
E:/Backup/Project/Chef_Repo/chef/lib/chef/knife.rb:474:in `run_with_pretty_exceptions'
E:/Backup/Project/Chef_Repo/chef/lib/chef/knife.rb:222:in `run'
E:/Backup/Project/Chef_Repo/chef/lib/chef/application/knife.rb:162:in `run'
E:/Backup/Project/Chef_Repo/chef/bin/knife:24:in `<top (required)>'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/bin/knife:23:in `load'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/bin/knife:23:in `<main>'
```

**Comment by dheerajd-msys** [comment]
We've fixed this issue in commit 8520a4ff1743214710e78900cc5bea897ce6bd72 of https://github.com/chef/knife-ec2/pull/587
