### ISSUE TITLE
knife ec2 server create fails with error undefined method `platform' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by dheerajd-msys** [chef/knife-ec2#593]
# Version:

knife-ec2 v1.0.0 and chef v15.1.8 on workstation

# Environment:

Doesn't matter

# Scenario:

```
bundle exec knife ec2 server create -I ami-005bdb005fb00e791 -N dh-ubu-16 --ssh-key dh-aws-key --flavor m4.large -c E:\Backup\Project\chef-starter\chef-repo\.chef\knife.rb -VV --yes --ephemeral "/dev/sdc" --ebs-optimized --ebs-size 8 --ebs-encrypted
```

# Steps to Reproduce:

Please run above command to create the server from workstation.

# Expected Result:

Server should get created and bootstrapped.

# Actual Result:

`undefined method `platform' for nil:NilClass (NoMethodError)`

# Stacktrace:
```
Traceback (most recent call last):
        11: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/bin/knife:23:in `<main>'
        10: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/bin/knife:23:in `load'
         9: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.8-universal-mingw32/bin/knife:24:in `<top (required)>'
         8: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.8-universal-mingw32/lib/chef/application/knife.rb:162:in `run'
         7: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.8-universal-mingw32/lib/chef/knife.rb:222:in `run'
         6: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.8-universal-mingw32/lib/chef/knife.rb:474:in `run_with_pretty_exceptions'
         5: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.8-universal-mingw32/lib/chef/local_mode.rb:42:in `with_server_connectivity'
         4: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.8-universal-mingw32/lib/chef/knife.rb:475:in `block in run_with_pretty_exceptions'
         3: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.8-universal-mingw32/lib/chef/knife/bootstrap.rb:557:in `run'
         2: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.8-universal-mingw32/lib/chef/knife/bootstrap.rb:752:in `validate_protocol!'
         1: from E:/Backup/Project/Chef_Repo/knife-ec2/lib/chef/knife/ec2_server_create.rb:1378:in `connection_protocol'
E:/Backup/Project/Chef_Repo/knife-ec2/lib/chef/knife/ec2_base.rb:186:in `is_image_windows?': undefined method `platform' for nil:NilClass (NoMethodError)
```

**Comment by dheerajd-msys** [comment]
Fixed in commit 942f03fd00c47370654e46e75501f9144b9f235e of https://github.com/chef/knife-ec2/pull/587
